.ALIASES
C_C1            C1(1=N00330 2=N00316 ) CN @HIGHPASSFILTERS.HPFilters(sch_1):INS278@ANALOG.C.Normal(chips)
R_R_Load          R_Load(1=N00316 2=0 ) CN @HIGHPASSFILTERS.HPFilters(sch_1):INS294@ANALOG.R.Normal(chips)
V_V1            V1(+=N00330 -=0 ) CN @HIGHPASSFILTERS.HPFilters(sch_1):INS340@SOURCE.VAC.Normal(chips)
R_R1            R1(1=N00930 2=N00836 ) CN @HIGHPASSFILTERS.HPFilters(sch_1):INS838@ANALOG.R.Normal(chips)
L_L1            L1(1=N00836 2=0 ) CN @HIGHPASSFILTERS.HPFilters(sch_1):INS858@ANALOG.L.Normal(chips)
R_R_Load1          R_Load1(1=N00836 2=0 ) CN @HIGHPASSFILTERS.HPFilters(sch_1):INS890@ANALOG.R.Normal(chips)
V_V2            V2(+=N00930 -=0 ) CN @HIGHPASSFILTERS.HPFilters(sch_1):INS934@SOURCE.VAC.Normal(chips)
.ENDALIASES
