.ALIASES
R_R1            R1(1=N00525 2=N00509 ) CN @LOWPASSFILTERS.LPFilters(sch_1):INS471@ANALOG.R.Normal(chips)
C_C1            C1(1=N00509 2=0 ) CN @LOWPASSFILTERS.LPFilters(sch_1):INS491@ANALOG.C.Normal(chips)
V_V1            V1(+=N00525 -=0 ) CN @LOWPASSFILTERS.LPFilters(sch_1):INS529@SOURCE.VAC.Normal(chips)
R_R_load          R_load(1=N00509 2=0 ) CN @LOWPASSFILTERS.LPFilters(sch_1):INS561@ANALOG.R.Normal(chips)
R_R_Load1          R_Load1(1=N00813 2=0 ) CN @LOWPASSFILTERS.LPFilters(sch_1):INS771@ANALOG.R.Normal(chips)
L_L1            L1(1=N00827 2=N00813 ) CN @LOWPASSFILTERS.LPFilters(sch_1):INS791@ANALOG.L.Normal(chips)
V_V2            V2(+=N00827 -=0 ) CN @LOWPASSFILTERS.LPFilters(sch_1):INS837@SOURCE.VAC.Normal(chips)
.ENDALIASES
